version: '3.8'

services:
  bitcoin:
    image: ruimarinho/bitcoin-core:25.0
    command:
      - -regtest=1
      - -server=1
      - -rpcuser=user
      - -rpcpassword=password
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
    ports:
      - "18443:18443"
    volumes:
      - bitcoin-data:/data

  network-indexer:
    build:
      context: ./network-indexer
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - RPC_HOST=bitcoin-regtest
      - RPC_PORT=18443
      - RPC_USER=user
      - RPC_PASSWORD=password
      - SOCKET_PATH=/tmp/network-utxos.sock
      - START_HEIGHT=${INDEXER_START_BLOCK:-0}
      - POLLING_RATE=${INDEXER_POLLING_RATE:-500}
      - MAX_BLOCKS_PER_BATCH=${INDEXER_MAX_BLOCKS:-200}
    networks:
      - bitcoin_network
    depends_on:
      - network-utxos
    volumes:
      - socket:/tmp

  network-utxos:
    build:
      context: ./network-utxos
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - HOST=0.0.0.0
      - PORT=5557
      - LOG_LEVEL=info
      - DATASOURCE=sqlite
      - SOCKET_PATH=/tmp/network-utxos.sock
    ports:
      - "5557:5557"
    networks:
      - bitcoin_network
    volumes:
      - utxo-data:/data
      - socket:/tmp

volumes:
  bitcoin-data:
  utxo-data:
  socket: