[package]
name = "network-shared"
version = "0.1.1"
edition = "2021"

[dependencies]
bincode.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true