[package]
name = "network-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin.workspace = true
bincode.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true